apiVersion: v1
kind: Secret
metadata:
  name: notification-service
  namespace: microservices
data:
  AMQP_USERNAME: ZGVmYXVsdA== #base64 for "default"
  AMQP_PASSWORD: ZGVmYXVsdA== #base64 for "default"
