apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
  namespace: microservices
data:
  HTTP_SERVER_URL: "0.0.0.0:4000"
  HTTP_SHUTDOWN_TIMEOUT: "5s"
  GIN_MODE: "release"

  AMQP_HOST: "rabbitmq.datastores.svc.cluster.local"
  AMQP_PORT: "5672"
  AMQP_CONNECTION_RETRY_INTERVAL_SECONDS: "5s"
  AMQP_CONNECTION_RETRY_ATTEMPTS: "10"
  AMQP_PUBLISH_TIMEOUT_SECONDS: "3s"
