apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway
  namespace: microservices
data:
  HTTP_SERVER_URL: "0.0.0.0:4000"
  HTTP_SERVER_SHUTDOWN_TIMEOUT: "5s"
  GIN_MODE: "release"

  USER_SERVICE_CLIENT_URL: "http://user-service:4000"
  USER_SERVICE_CLIENT_TIMEOUT: "2s"
